version: '3.2'

services:
  gosqlite:
    networks:
      mesh:
        aliases:
          - gosqlite
    image: gosqlite:latest
    ports:
      - '9321:9321'
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/visionbot-secret-key.json
    volumes:
      - ./schema.db:/root/schema.db
      - ./files:/root/files
      - ./visionbot-secret-key.json:/root/visionbot-secret-key.json
networks:
  mesh: {}
    
